sudo:     required
dist:     trusty
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r/test
          package:
            - g++-6
        update-alternatives:
          --install /usr/bin/gcc gcc /usr/bin/gcc-6 90
          --install /usr/bin/g++ g++ /usr/bin/g++-6 90
      env:
        COMPILER=g++ BUILD_CONFIGURATION=Debug
        COMPILER=g++ BUILD_CONFIGURATION=Release

before_install:
    - sudo apt-get update -qq

install:
    - sudo apt-get install libboost-all-dev
    - sudo apt-get install -qq lcov
    - bash ci/travis/install-linux.sh

script:
    - mkdir build
    - pushd build
    - cmake .. -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION
    - make
    - popd
    - ./GoogleTest

after_success:
    - bash <(curl -s https://codecov.io/bash)
