#...............................................................................
#
# Travis CI
#
#...............................................................................

sudo:     required
dist:     trusty
language: cpp

os: linux

matrix:
  include:

    ##########################################################################
    # GCC on Linux
    ##########################################################################

    # GCC 6
    - env: C_COMPILER=gcc-6 CXX_COMPILER=g++-6 BUILD_TYPE=Debug WITH_TESTS=ON
      compiler: gcc
      addons: &gcc6
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - libboost-all-dev
            - lcov

    - env: C_COMPILER=gcc-6 CXX_COMPILER=g++-6 BUILD_TYPE=Release
      compiler: gcc
      addons: *gcc6

    ##########################################################################
    # Clang on Linux
    ##########################################################################

    # Clang 5.0
    - env: C_COMPILER=clang-5.0 CXX_COMPILER=clang++-5.0 BUILD_TYPE=Debug WITH_TESTS=ON
      compiler: clang
      addons: &clang50
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - gcc-6
            - g++-6
            - clang-5.0
            - libboost-all-dev
            - lcov

    - env: C_COMPILER=clang-5.0 CXX_COMPILER=clang++-5.0 BUILD_TYPE=Release
      compiler: clang
      addons: *clang50


before_install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90


install:
  - bash ci/travis/install-linux.sh


script:
  - mkdir build
  - pushd build
  - cmake .. -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DWITH_TESTS=$WITH_TESTS
  - make
  - if [ "$WITH_TESTS" == "ON" ]; then
      make test;
      if [ "$C_COMPILER" == "gcc-6" ] && [ "$CXX_COMPILER" == "g++-6" ]; then
        make test_conf_manager_coverage;
        make test_safe_queue_coverage;
      fi
    fi
  - popd


after_success:
  - if [ "$BUILD_TYPE" == "Debug" ] && [ "$WITH_TESTS" == "ON" ] && [ "$C_COMPILER" == "gcc-6" ] && [ "$CXX_COMPILER" == "g++-6" ]; then
      bash <(curl -s https://codecov.io/bash);
    fi
