#
#  Description: General configuration file
#

#--- General Server Settings ---
Server:
  #--- Server name ---
  Name: 'server'

  #--- Connection endpoint settings ---
  Connection endpiont:
    ip_addr: '0.0.0.0'
    port: '12345'

  #--- Paths ---
  Paths:
    #--- Path to log file ---
    Log:
      logfile: '/var/log/server/server_log'

    #--- Path to pid file ---
    Pid:
      pidfile: '/var/run/server.pid'
